# TODO: Complete the Horizontal Pod Autoscaler configuration
# This enables automatic scaling based on CPU/memory usage

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: rate-limiter-hpa
spec:
  # TODO: Reference the deployment to scale
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: rate-limiter-deployment

  # TODO: Set min and max replica counts
  minReplicas: 2
  maxReplicas: 10

  # TODO: Configure scaling metrics
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70

    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80

  # TODO: Configure scaling behavior (production pattern)
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
        - type: Percent
          value: 50
          periodSeconds: 30

    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
        - type: Percent
          value: 10
          periodSeconds: 60
